# Generated by Django 3.2.14 on 2022-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_video_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VideoProxy",
        ),
        migrations.CreateModel(
            name="VideoAllProxy",
            fields=[],
            options={
                "verbose_name": "All Video",
                "verbose_name_plural": "All Videos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("videos.video",),
        ),
        migrations.CreateModel(
            name="VideoPublishedProxy",
            fields=[],
            options={
                "verbose_name": "Published Video",
                "verbose_name_plural": "Published Videos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("videos.video",),
        ),
        migrations.AddField(
            model_name="video",
            name="state",
            field=models.CharField(
                choices=[("PU", "Publish"), ("DR", "Draft")], default="DR", max_length=2
            ),
        ),
    ]
