# Generated by Django 3.2.14 on 2022-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_auto_20220813_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
